"""Generate words.json with ~3000 common daily English vocabulary words.

Strategy: Create compact word list first, then enrich with dictionary API data.
"""
import json
import os

WORDS_JSON = os.path.join(os.path.dirname(__file__), "data", "words.json")

# Compact format: (word, pos, meaning_cn)
# phonetic, example_en, example_cn will be filled by enrich_words.py

FOOD = [
    ("apple","noun","苹果"),("banana","noun","香蕉"),("orange","noun","橙子"),("grape","noun","葡萄"),
    ("strawberry","noun","草莓"),("watermelon","noun","西瓜"),("peach","noun","桃子"),("lemon","noun","柠檬"),
    ("cherry","noun","樱桃"),("mango","noun","芒果"),("pineapple","noun","菠萝"),("pear","noun","梨"),
    ("blueberry","noun","蓝莓"),("coconut","noun","椰子"),("plum","noun","李子"),("kiwi","noun","猕猴桃"),
    ("fig","noun","无花果"),("pomegranate","noun","石榴"),("apricot","noun","杏"),("avocado","noun","牛油果"),
    ("tomato","noun","番茄"),("potato","noun","土豆"),("onion","noun","洋葱"),("carrot","noun","胡萝卜"),
    ("cabbage","noun","卷心菜"),("garlic","noun","大蒜"),("pepper","noun","辣椒；胡椒"),("mushroom","noun","蘑菇"),
    ("corn","noun","玉米"),("lettuce","noun","生菜"),("cucumber","noun","黄瓜"),("broccoli","noun","西兰花"),
    ("spinach","noun","菠菜"),("eggplant","noun","茄子"),("celery","noun","芹菜"),("pumpkin","noun","南瓜"),
    ("radish","noun","萝卜"),("pea","noun","豌豆"),("bean","noun","豆子"),("asparagus","noun","芦笋"),
    ("rice","noun","米饭"),("bread","noun","面包"),("noodle","noun","面条"),("pasta","noun","意面"),
    ("flour","noun","面粉"),("oat","noun","燕麦"),("wheat","noun","小麦"),("barley","noun","大麦"),
    ("sugar","noun","糖"),("salt","noun","盐"),("butter","noun","黄油"),("cheese","noun","奶酪"),
    ("milk","noun","牛奶"),("egg","noun","鸡蛋"),("cream","noun","奶油"),("yogurt","noun","酸奶"),
    ("chicken","noun","鸡肉"),("beef","noun","牛肉"),("pork","noun","猪肉"),("lamb","noun","羊肉"),
    ("fish","noun","鱼"),("shrimp","noun","虾"),("salmon","noun","三文鱼"),("tuna","noun","金枪鱼"),
    ("steak","noun","牛排"),("sausage","noun","香肠"),("bacon","noun","培根"),("ham","noun","火腿"),
    ("soup","noun","汤"),("salad","noun","沙拉"),("sandwich","noun","三明治"),("burger","noun","汉堡"),
    ("pizza","noun","披萨"),("cake","noun","蛋糕"),("cookie","noun","饼干"),("pie","noun","派"),
    ("ice cream","noun","冰淇淋"),("chocolate","noun","巧克力"),("candy","noun","糖果"),("pastry","noun","糕点"),
    ("coffee","noun","咖啡"),("tea","noun","茶"),("juice","noun","果汁"),("water","noun","水"),
    ("beer","noun","啤酒"),("wine","noun","葡萄酒"),("soda","noun","汽水"),("smoothie","noun","冰沙"),
    ("breakfast","noun","早餐"),("lunch","noun","午餐"),("dinner","noun","晚餐"),("snack","noun","零食"),
    ("appetizer","noun","开胃菜"),("dessert","noun","甜点"),("recipe","noun","食谱"),("menu","noun","菜单"),
    ("dish","noun","菜肴"),("sauce","noun","酱汁"),("dressing","noun","沙拉酱"),("spice","noun","香料"),
    ("ginger","noun","姜"),("cinnamon","noun","肉桂"),("mint","noun","薄荷"),("basil","noun","罗勒"),
    ("olive","noun","橄榄"),("vinegar","noun","醋"),("soy sauce","noun","酱油"),("honey","noun","蜂蜜"),
    ("jam","noun","果酱"),("peanut","noun","花生"),("almond","noun","杏仁"),("walnut","noun","核桃"),
    ("cashew","noun","腰果"),("cereal","noun","麦片"),("toast","noun","吐司"),("dumpling","noun","饺子"),
    ("sushi","noun","寿司"),("curry","noun","咖喱"),("stew","noun","炖菜"),("barbecue","noun","烧烤"),
    ("cook","verb","烹饪"),("bake","verb","烘焙"),("fry","verb","油炸；煎"),("boil","verb","煮沸"),
    ("grill","verb","烧烤"),("steam","verb","蒸"),("roast","verb","烤"),("chop","verb","切碎"),
    ("slice","verb","切片"),("stir","verb","搅拌"),("mix","verb","混合"),("pour","verb","倒"),
    ("taste","verb","品尝"),("serve","verb","上菜"),("peel","verb","剥皮"),("blend","verb","搅拌"),
    ("marinate","verb","腌制"),("season","verb","调味"),("garnish","verb","装饰"),("kitchen","noun","厨房"),
    ("oven","noun","烤箱"),("microwave","noun","微波炉"),("refrigerator","noun","冰箱"),("freezer","noun","冷冻室"),
    ("pan","noun","平底锅"),("pot","noun","锅"),("plate","noun","盘子"),("bowl","noun","碗"),
    ("cup","noun","杯子"),("spoon","noun","勺子"),("fork","noun","叉子"),("knife","noun","刀"),
    ("chopstick","noun","筷子"),("napkin","noun","餐巾"),("appetite","noun","食欲"),("hunger","noun","饥饿"),
    ("thirst","noun","口渴"),("portion","noun","份量"),("ingredient","noun","食材"),("flavor","noun","味道"),
    ("cuisine","noun","菜系"),("buffet","noun","自助餐"),("takeaway","noun","外卖"),("diet","noun","饮食"),
    ("protein","noun","蛋白质"),("vitamin","noun","维生素"),("calorie","noun","卡路里"),("fiber","noun","纤维"),
    ("mineral","noun","矿物质"),("nutrition","noun","营养"),("carbohydrate","noun","碳水化合物"),
    ("delicious","adj","美味的"),("spicy","adj","辣的"),("sweet","adj","甜的"),("sour","adj","酸的"),
    ("bitter","adj","苦的"),("salty","adj","咸的"),("fresh","adj","新鲜的"),("raw","adj","生的"),
    ("ripe","adj","成熟的"),("organic","adj","有机的"),("hungry","adj","饥饿的"),("thirsty","adj","口渴的"),
    ("nutritious","adj","有营养的"),("appetizing","adj","诱人的"),("vegetarian","adj","素食的"),
    ("crave","verb","渴望"),("chew","verb","咀嚼"),("swallow","verb","吞咽"),("sip","verb","小口喝"),
    ("dine","verb","用餐"),("starve","verb","挨饿"),("nourish","verb","滋养"),("digest","verb","消化"),
    ("waiter","noun","服务员"),("bill","noun","账单"),("tip","noun","小费"),("reservation","noun","预订"),
    ("beverage","noun","饮料"),("leftover","noun","剩菜"),("canteen","noun","食堂"),("cafeteria","noun","自助餐厅"),
    ("tofu","noun","豆腐"),("lentil","noun","扁豆"),("grain","noun","谷物"),("crop","noun","农作物"),
    ("harvest","noun","收获"),("feast","noun","盛宴"),("consume","verb","食用；消费"),
]

TRAVEL = [
    ("passport","noun","护照"),("visa","noun","签证"),("luggage","noun","行李"),("suitcase","noun","手提箱"),
    ("backpack","noun","背包"),("ticket","noun","票"),("flight","noun","航班"),("airport","noun","机场"),
    ("departure","noun","出发"),("arrival","noun","到达"),("boarding","noun","登机"),("gate","noun","登机口"),
    ("terminal","noun","航站楼"),("check-in","noun","值机"),("baggage claim","noun","行李提取"),
    ("customs","noun","海关"),("duty-free","adj","免税的"),("hotel","noun","酒店"),("motel","noun","汽车旅馆"),
    ("hostel","noun","青年旅舍"),("reservation","noun","预订"),("reception","noun","前台"),
    ("room service","noun","客房服务"),("sightseeing","noun","观光"),("tourist","noun","游客"),
    ("tour","noun","旅行；游览"),("guide","noun","导游"),("map","noun","地图"),("destination","noun","目的地"),
    ("itinerary","noun","行程"),("souvenir","noun","纪念品"),("adventure","noun","冒险"),("explore","verb","探索"),
    ("abroad","adv","在国外"),("journey","noun","旅程"),("voyage","noun","航行"),("cruise","noun","邮轮旅行"),
    ("excursion","noun","短途旅行"),("expedition","noun","探险"),("landmark","noun","地标"),
    ("monument","noun","纪念碑"),("museum","noun","博物馆"),("gallery","noun","画廊"),("temple","noun","寺庙"),
    ("castle","noun","城堡"),("beach","noun","海滩"),("island","noun","岛屿"),("mountain","noun","山"),
    ("forest","noun","森林"),("lake","noun","湖"),("waterfall","noun","瀑布"),("valley","noun","山谷"),
    ("coast","noun","海岸"),("cliff","noun","悬崖"),("scenic","adj","风景优美的"),("landscape","noun","风景"),
    ("brochure","noun","宣传册"),("currency","noun","货币"),("exchange rate","noun","汇率"),
    ("compass","noun","指南针"),("navigate","verb","导航"),("direction","noun","方向"),("route","noun","路线"),
    ("highway","noun","高速公路"),("embassy","noun","大使馆"),("foreign","adj","外国的"),
    ("domestic","adj","国内的"),("layover","noun","中转"),("delay","noun","延误"),("cancel","verb","取消"),
    ("accommodation","noun","住宿"),("resort","noun","度假村"),("campsite","noun","露营地"),
    ("tent","noun","帐篷"),("backpacker","noun","背包客"),("hiker","noun","远足者"),
    ("transportation","noun","交通"),("companion","noun","旅伴"),("wander","verb","漫步"),
    ("travel","verb","旅行"),("pack","verb","打包"),("unpack","verb","拆包"),("board","verb","登机"),
    ("land","verb","降落"),("depart","verb","出发"),("arrive","verb","到达"),("overseas","adv","在海外"),
    ("fare","noun","票价"),("transfer","noun","转乘"),("jet lag","noun","时差"),("hike","verb","远足"),
    ("camp","verb","露营"),("visit","verb","参观"),("discover","verb","发现"),("experience","noun","体验"),
    ("ferry","noun","渡轮"),("subway","noun","地铁"),("tram","noun","有轨电车"),("taxi","noun","出租车"),
    ("cab","noun","出租车"),("shuttle","noun","班车"),("coach","noun","长途客车"),("carriage","noun","车厢"),
    ("platform","noun","站台"),("station","noun","车站"),("timetable","noun","时刻表"),
    ("schedule","noun","日程表"),("departure lounge","noun","候机室"),("runway","noun","跑道"),
    ("pilot","noun","飞行员"),("passenger","noun","乘客"),("crew","noun","乘务组"),("aisle","noun","过道"),
    ("window seat","noun","靠窗座位"),("aisle seat","noun","靠走道座位"),("seatbelt","noun","安全带"),
    ("takeoff","noun","起飞"),("landing","noun","降落"),("turbulence","noun","颠簸"),("immigration","noun","入境检查"),
    ("border","noun","边界"),("embark","verb","上船"),("disembark","verb","下船"),("port","noun","港口"),
    ("harbor","noun","港湾"),("dock","noun","码头"),("anchor","noun","锚"),("voyage","noun","航海"),
    ("expedition","noun","远征"),("souvenir","noun","纪念品"),("postcard","noun","明信片"),
    ("camera","noun","相机"),("photograph","noun","照片"),("selfie","noun","自拍"),
    ("attraction","noun","景点"),("heritage","noun","遗产"),("ruins","noun","遗迹"),
    ("cathedral","noun","大教堂"),("palace","noun","宫殿"),("statue","noun","雕像"),
    ("fountain","noun","喷泉"),("square","noun","广场"),("plaza","noun","广场"),
    ("market","noun","市场"),("night market","noun","夜市"),("street food","noun","街头小吃"),
    ("local","adj","当地的"),("native","adj","本地的"),("exotic","adj","异国情调的"),
    ("tour","verb","游览"),("backpack","verb","背包旅行"),("cruise","verb","乘船游览"),
    ("expedition","noun","探险"),("wander","verb","漫步"),("roam","verb","漫游"),
    ("trek","verb","长途跋涉"),("safari","noun","狩猎旅行"),("pilgrimage","noun","朝圣"),
]

SHOPPING = [
    ("shop","noun","商店"),("store","noun","商店"),("mall","noun","购物中心"),("market","noun","市场"),
    ("supermarket","noun","超市"),("boutique","noun","精品店"),("discount","noun","折扣"),("sale","noun","促销"),
    ("bargain","noun","便宜货"),("price","noun","价格"),("cost","noun","费用"),("cheap","adj","便宜的"),
    ("expensive","adj","昂贵的"),("afford","verb","买得起"),("purchase","noun","购买"),("buy","verb","买"),
    ("sell","verb","卖"),("pay","verb","付款"),("cash","noun","现金"),("credit card","noun","信用卡"),
    ("receipt","noun","收据"),("refund","noun","退款"),("exchange","noun","换货"),("return","verb","退货"),
    ("customer","noun","顾客"),("shopkeeper","noun","店主"),("clerk","noun","店员"),("brand","noun","品牌"),
    ("quality","noun","质量"),("product","noun","产品"),("item","noun","物品"),("size","noun","尺码"),
    ("color","noun","颜色"),("style","noun","风格"),("design","noun","设计"),("fashion","noun","时尚"),
    ("trend","noun","趋势"),("popular","adj","受欢迎的"),("luxury","noun","奢侈品"),("fitting room","noun","试衣间"),
    ("try on","verb","试穿"),("grocery","noun","杂货"),("cart","noun","购物车"),("basket","noun","篮子"),
    ("checkout","noun","收银台"),("coupon","noun","优惠券"),("voucher","noun","代金券"),("promotion","noun","促销"),
    ("deal","noun","交易"),("offer","noun","优惠"),("wholesale","noun","批发"),("retail","noun","零售"),
    ("online shopping","noun","网购"),("delivery","noun","配送"),("shipping","noun","运费"),("order","noun","订单"),
    ("catalog","noun","商品目录"),("warranty","noun","保修"),("guarantee","noun","保证"),("sample","noun","样品"),
    ("gift","noun","礼物"),("wrap","verb","包装"),("bag","noun","袋子"),("barcode","noun","条形码"),
    ("shelf","noun","货架"),("aisle","noun","过道"),("display","noun","展示"),("stock","noun","库存"),
    ("supply","noun","供应"),("import","noun","进口"),("export","noun","出口"),("vendor","noun","小贩"),
    ("merchandise","noun","商品"),("commodity","noun","商品"),("outlet","noun","折扣店"),
    ("convenience store","noun","便利店"),("pharmacy","noun","药店"),("bakery","noun","面包店"),
    ("butcher","noun","肉铺"),("florist","noun","花店"),("stationery","noun","文具"),
    ("cosmetic","noun","化妆品"),("perfume","noun","香水"),("jewelry","noun","珠宝"),
    ("electronic","adj","电子的"),("appliance","noun","家电"),("furniture","noun","家具"),
    ("window shopping","noun","只逛不买"),("on sale","adj","打折中"),("out of stock","adj","缺货"),
    ("in stock","adj","有货"),("clearance","noun","清仓"),("bargain","verb","讨价还价"),
    ("haggle","verb","讨价还价"),("compare","verb","比较"),("choose","verb","选择"),("select","verb","挑选"),
    ("prefer","verb","偏好"),("recommend","verb","推荐"),("browse","verb","浏览"),("search","verb","搜索"),
    ("scan","verb","扫描"),("purchase","verb","购买"),("charge","verb","收费"),("owe","verb","欠"),
    ("change","noun","零钱"),("installment","noun","分期付款"),("deposit","noun","押金"),
    ("mortgage","noun","贷款"),("budget","noun","预算"),("expense","noun","支出"),
    ("affordable","adj","负担得起的"),("pricey","adj","昂贵的"),("valuable","adj","有价值的"),
    ("worthwhile","adj","值得的"),("economical","adj","经济实惠的"),
]

HOME = [
    ("house","noun","房子"),("home","noun","家"),("apartment","noun","公寓"),("flat","noun","公寓(英式)"),
    ("room","noun","房间"),("bedroom","noun","卧室"),("living room","noun","客厅"),("kitchen","noun","厨房"),
    ("bathroom","noun","浴室"),("dining room","noun","餐厅"),("study","noun","书房"),("garage","noun","车库"),
    ("garden","noun","花园"),("balcony","noun","阳台"),("basement","noun","地下室"),("attic","noun","阁楼"),
    ("stairs","noun","楼梯"),("hallway","noun","走廊"),("door","noun","门"),("window","noun","窗户"),
    ("wall","noun","墙"),("floor","noun","地板"),("ceiling","noun","天花板"),("roof","noun","屋顶"),
    ("fence","noun","栅栏"),("gate","noun","大门"),("yard","noun","院子"),("driveway","noun","车道"),
    ("sofa","noun","沙发"),("couch","noun","长沙发"),("chair","noun","椅子"),("table","noun","桌子"),
    ("desk","noun","书桌"),("bed","noun","床"),("wardrobe","noun","衣柜"),("closet","noun","壁橱"),
    ("drawer","noun","抽屉"),("shelf","noun","架子"),("cabinet","noun","柜子"),("mirror","noun","镜子"),
    ("lamp","noun","灯"),("curtain","noun","窗帘"),("carpet","noun","地毯"),("rug","noun","小地毯"),
    ("blanket","noun","毯子"),("pillow","noun","枕头"),("mattress","noun","床垫"),("towel","noun","毛巾"),
    ("sheet","noun","床单"),("cushion","noun","靠垫"),("washing machine","noun","洗衣机"),
    ("dryer","noun","烘干机"),("vacuum","noun","吸尘器"),("heater","noun","暖气"),
    ("air conditioner","noun","空调"),("iron","noun","熨斗"),("lock","noun","锁"),("key","noun","钥匙"),
    ("bell","noun","门铃"),("socket","noun","插座"),("switch","noun","开关"),("pipe","noun","管道"),
    ("drain","noun","排水口"),("faucet","noun","水龙头"),("tile","noun","瓷砖"),("paint","noun","油漆"),
    ("clean","verb","打扫"),("tidy","verb","整理"),("organize","verb","组织"),("dust","verb","除尘"),
    ("mop","verb","拖地"),("sweep","verb","扫地"),("scrub","verb","擦洗"),("wipe","verb","擦拭"),
    ("laundry","noun","洗衣"),("chore","noun","家务"),("housework","noun","家务活"),
    ("neighbor","noun","邻居"),("community","noun","社区"),("property","noun","房产"),
    ("rent","noun","租金"),("landlord","noun","房东"),("tenant","noun","租户"),("lease","noun","租约"),
    ("move","verb","搬家"),("settle","verb","安顿"),("cozy","adj","温馨的"),("spacious","adj","宽敞的"),
    ("cramped","adj","狭窄的"),("messy","adj","凌乱的"),("neat","adj","整洁的"),
    ("furnished","adj","带家具的"),("storage","noun","储物"),("garbage","noun","垃圾"),
    ("recycle","verb","回收"),("trash","noun","垃圾"),("bin","noun","垃圾桶"),("plug","noun","插头"),
    ("cable","noun","线缆"),("remote","noun","遥控器"),("doorbell","noun","门铃"),
    ("porch","noun","门廊"),("patio","noun","露台"),("fireplace","noun","壁炉"),
    ("staircase","noun","楼梯"),("elevator","noun","电梯"),("corridor","noun","走廊"),
    ("pantry","noun","食品储藏室"),("candle","noun","蜡烛"),("vase","noun","花瓶"),
    ("frame","noun","相框"),("knob","noun","门把手"),("handle","noun","把手"),("hinge","noun","铰链"),
    ("renovate","verb","翻修"),("repair","verb","修理"),("fix","verb","修复"),("decorate","verb","装饰"),
    ("polish","verb","抛光"),("relocate","verb","重新安置"),("mortgage","noun","房贷"),
    ("cushion","noun","靠垫"),("pillowcase","noun","枕套"),("bedspread","noun","床罩"),
    ("thermostat","noun","温控器"),("chimney","noun","烟囱"),("intercom","noun","对讲机"),
    ("utility room","noun","杂物间"),("linen","noun","家用织品"),
]

BODY = [
    ("head","noun","头"),("hair","noun","头发"),("face","noun","脸"),("eye","noun","眼睛"),
    ("ear","noun","耳朵"),("nose","noun","鼻子"),("mouth","noun","嘴"),("lip","noun","嘴唇"),
    ("tooth","noun","牙齿"),("tongue","noun","舌头"),("neck","noun","脖子"),("shoulder","noun","肩膀"),
    ("arm","noun","手臂"),("elbow","noun","肘"),("wrist","noun","手腕"),("hand","noun","手"),
    ("finger","noun","手指"),("thumb","noun","拇指"),("nail","noun","指甲"),("palm","noun","手掌"),
    ("chest","noun","胸膛"),("back","noun","背"),("stomach","noun","胃"),("waist","noun","腰"),
    ("hip","noun","臀部"),("leg","noun","腿"),("knee","noun","膝盖"),("ankle","noun","脚踝"),
    ("foot","noun","脚"),("toe","noun","脚趾"),("skin","noun","皮肤"),("bone","noun","骨头"),
    ("muscle","noun","肌肉"),("blood","noun","血液"),("heart","noun","心脏"),("brain","noun","大脑"),
    ("lung","noun","肺"),("liver","noun","肝"),("kidney","noun","肾"),("spine","noun","脊柱"),
    ("joint","noun","关节"),("vein","noun","静脉"),("nerve","noun","神经"),("pulse","noun","脉搏"),
    ("breath","noun","呼吸"),("sight","noun","视觉"),("hearing","noun","听觉"),("smell","noun","嗅觉"),
    ("taste","noun","味觉"),("touch","noun","触觉"),("posture","noun","姿势"),("wrinkle","noun","皱纹"),
    ("scar","noun","伤疤"),("bruise","noun","瘀伤"),("wound","noun","伤口"),("fracture","noun","骨折"),
    ("ache","noun","疼痛"),("pain","noun","痛苦"),("symptom","noun","症状"),("fatigue","noun","疲劳"),
    ("immunity","noun","免疫力"),("metabolism","noun","新陈代谢"),("digestion","noun","消化"),
    ("breathe","verb","呼吸"),("blink","verb","眨眼"),("swallow","verb","吞咽"),("chew","verb","咀嚼"),
    ("sweat","verb","出汗"),("shiver","verb","颤抖"),("sneeze","verb","打喷嚏"),("cough","verb","咳嗽"),
    ("yawn","verb","打哈欠"),("stretch","verb","伸展"),("bend","verb","弯曲"),("twist","verb","扭伤"),
    ("scratch","verb","抓挠"),("rub","verb","摩擦"),("squeeze","verb","挤压"),("grab","verb","抓住"),
    ("release","verb","释放"),("frown","verb","皱眉"),("smile","verb","微笑"),("nod","verb","点头"),
    ("shake","verb","摇动"),("wave","verb","挥手"),("clap","verb","鼓掌"),("point","verb","指向"),
    ("complexion","noun","面色"),("forehead","noun","额头"),("chin","noun","下巴"),("cheek","noun","脸颊"),
    ("eyebrow","noun","眉毛"),("eyelash","noun","睫毛"),("pupil","noun","瞳孔"),("jaw","noun","下颌"),
    ("rib","noun","肋骨"),("pelvis","noun","骨盆"),("thigh","noun","大腿"),("calf","noun","小腿"),
    ("heel","noun","脚后跟"),("sole","noun","脚底"),("arch","noun","足弓"),("fist","noun","拳头"),
    ("knuckle","noun","指关节"),("forearm","noun","前臂"),("armpit","noun","腋窝"),
    ("collarbone","noun","锁骨"),("shoulder blade","noun","肩胛骨"),("spine","noun","脊柱"),
    ("appendix","noun","阑尾"),("gallbladder","noun","胆囊"),("bladder","noun","膀胱"),
    ("intestine","noun","肠"),("artery","noun","动脉"),("capillary","noun","毛细血管"),
    ("cartilage","noun","软骨"),("ligament","noun","韧带"),("tendon","noun","肌腱"),
    ("skull","noun","头骨"),("jawbone","noun","颌骨"),("hipbone","noun","髋骨"),
]

WEATHER = [
    ("weather","noun","天气"),("climate","noun","气候"),("temperature","noun","温度"),("season","noun","季节"),
    ("spring","noun","春天"),("summer","noun","夏天"),("autumn","noun","秋天"),("winter","noun","冬天"),
    ("rain","noun","雨"),("snow","noun","雪"),("wind","noun","风"),("cloud","noun","云"),
    ("sun","noun","太阳"),("fog","noun","雾"),("storm","noun","暴风雨"),("thunder","noun","雷"),
    ("lightning","noun","闪电"),("hail","noun","冰雹"),("frost","noun","霜"),("dew","noun","露水"),
    ("humidity","noun","湿度"),("breeze","noun","微风"),("gale","noun","大风"),("hurricane","noun","飓风"),
    ("tornado","noun","龙卷风"),("typhoon","noun","台风"),("drought","noun","干旱"),("flood","noun","洪水"),
    ("rainbow","noun","彩虹"),("sunshine","noun","阳光"),("cloudy","adj","多云的"),("sunny","adj","晴朗的"),
    ("rainy","adj","下雨的"),("snowy","adj","下雪的"),("windy","adj","有风的"),("foggy","adj","有雾的"),
    ("cold","adj","冷的"),("hot","adj","热的"),("warm","adj","温暖的"),("cool","adj","凉爽的"),
    ("freezing","adj","极冷的"),("boiling","adj","极热的"),("mild","adj","温和的"),("humid","adj","潮湿的"),
    ("dry","adj","干燥的"),("wet","adj","潮湿的"),("chilly","adj","微冷的"),("sweltering","adj","酷热的"),
    ("overcast","adj","阴天的"),("clear","adj","晴朗的"),("pour","verb","倾盆大雨"),("drizzle","verb","毛毛雨"),
    ("shower","noun","阵雨"),("blizzard","noun","暴风雪"),("sleet","noun","雨夹雪"),
    ("mist","noun","薄雾"),("smog","noun","雾霾"),("dust","noun","灰尘"),("sandstorm","noun","沙尘暴"),
    ("heatwave","noun","热浪"),("cold snap","noun","寒潮"),("forecast","noun","天气预报"),
    ("meteorologist","noun","气象学家"),("barometer","noun","气压计"),("thermometer","noun","温度计"),
    ("atmosphere","noun","大气层"),("ozone","noun","臭氧"),("UV index","noun","紫外线指数"),
    ("precipitation","noun","降水量"),("evaporate","verb","蒸发"),("condense","verb","凝结"),
    ("freeze","verb","结冰"),("thaw","verb","融化"),("melt","verb","融化"),("blow","verb","吹"),
    ("shine","verb","照耀"),("rise","verb","升起"),("set","verb","落下"),
    ("dawn","noun","黎明"),("dusk","noun","黄昏"),("twilight","noun","暮光"),("midnight","noun","午夜"),
    ("daylight","noun","日光"),("shadow","noun","影子"),("shade","noun","阴凉"),("exposure","noun","暴露"),
    ("global warming","noun","全球变暖"),("greenhouse effect","noun","温室效应"),
    ("air pressure","noun","气压"),("wind chill","noun","风寒指数"),
    ("visibility","noun","能见度"),("climate change","noun","气候变化"),
]

EMOTION = [
    ("happy","adj","快乐的"),("sad","adj","悲伤的"),("angry","adj","生气的"),("afraid","adj","害怕的"),
    ("excited","adj","兴奋的"),("nervous","adj","紧张的"),("surprised","adj","惊讶的"),
    ("disappointed","adj","失望的"),("proud","adj","骄傲的"),("ashamed","adj","羞耻的"),
    ("guilty","adj","内疚的"),("jealous","adj","嫉妒的"),("lonely","adj","孤独的"),
    ("grateful","adj","感恩的"),("hopeful","adj","有希望的"),("desperate","adj","绝望的"),
    ("calm","adj","平静的"),("anxious","adj","焦虑的"),("relaxed","adj","放松的"),
    ("stressed","adj","压力大的"),("bored","adj","无聊的"),("confused","adj","困惑的"),
    ("embarrassed","adj","尴尬的"),("frustrated","adj","沮丧的"),("scared","adj","恐惧的"),
    ("terrified","adj","极度恐惧的"),("delighted","adj","高兴的"),("thrilled","adj","激动的"),
    ("miserable","adj","痛苦的"),("depressed","adj","抑郁的"),("content","adj","满足的"),
    ("satisfied","adj","满意的"),("dissatisfied","adj","不满意的"),("indifferent","adj","漠不关心的"),
    ("sympathetic","adj","同情的"),("compassionate","adj","有同情心的"),("envious","adj","羡慕的"),
    ("resentful","adj","怨恨的"),("bitter","adj","怨恨的"),("regretful","adj","后悔的"),
    ("nostalgic","adj","怀旧的"),("homesick","adj","想家的"),("relieved","adj","宽慰的"),
    ("shocked","adj","震惊的"),("amazed","adj","惊叹的"),("curious","adj","好奇的"),
    ("passionate","adj","热情的"),("enthusiastic","adj","热心的"),("optimistic","adj","乐观的"),
    ("pessimistic","adj","悲观的"),("skeptical","adj","怀疑的"),("suspicious","adj","可疑的"),
    ("trust","noun","信任"),("doubt","noun","怀疑"),("faith","noun","信念"),("belief","noun","信仰"),
    ("hope","noun","希望"),("fear","noun","恐惧"),("courage","noun","勇气"),("bravery","noun","勇敢"),
    ("joy","noun","喜悦"),("sorrow","noun","悲伤"),("grief","noun","悲痛"),("anger","noun","愤怒"),
    ("rage","noun","暴怒"),("fury","noun","狂怒"),("disgust","noun","厌恶"),("shame","noun","羞耻"),
    ("pride","noun","自豪"),("guilt","noun","内疚"),("envy","noun","嫉妒"),("love","noun","爱"),
    ("hate","noun","恨"),("affection","noun","喜爱"),("passion","noun","热情"),("desire","noun","欲望"),
    ("frustration","noun","挫败"),("disappointment","noun","失望"),("excitement","noun","兴奋"),
    ("enthusiasm","noun","热情"),("satisfaction","noun","满足"),("comfort","noun","安慰"),
    ("worry","noun","担忧"),("anxiety","noun","焦虑"),("stress","noun","压力"),
    ("relief","noun","宽慰"),("surprise","noun","惊喜"),("shock","noun","震惊"),
    ("embarrassment","noun","尴尬"),("confusion","noun","困惑"),("curiosity","noun","好奇心"),
    ("admiration","noun","钦佩"),("respect","noun","尊重"),("gratitude","noun","感激"),
    ("appreciation","noun","欣赏"),("sympathy","noun","同情"),("empathy","noun","共情"),
    ("feel","verb","感觉"),("experience","verb","经历"),("express","verb","表达"),
    ("hide","verb","隐藏"),("reveal","verb","揭示"),("cope","verb","应对"),
    ("overcome","verb","克服"),("endure","verb","忍受"),("suffer","verb","受苦"),
    ("enjoy","verb","享受"),("appreciate","verb","感激"),("miss","verb","想念"),
    ("forgive","verb","原谅"),("regret","verb","后悔"),("resent","verb","怨恨"),
    ("admire","verb","钦佩"),("despise","verb","鄙视"),("adore","verb","爱慕"),
    ("comfort","verb","安慰"),("encourage","verb","鼓励"),("support","verb","支持"),
    ("upset","verb","使心烦"),("annoy","verb","使烦恼"),("irritate","verb","激怒"),
    ("depress","verb","使沮丧"),("inspire","verb","激励"),("motivate","verb","激发"),
]

WORK = [
    ("job","noun","工作"),("career","noun","职业"),("profession","noun","专业"),("occupation","noun","职业"),
    ("office","noun","办公室"),("colleague","noun","同事"),("boss","noun","老板"),("employee","noun","雇员"),
    ("employer","noun","雇主"),("manager","noun","经理"),("director","noun","总监"),("supervisor","noun","主管"),
    ("assistant","noun","助手"),("secretary","noun","秘书"),("intern","noun","实习生"),("trainee","noun","培训生"),
    ("staff","noun","员工"),("personnel","noun","人事"),("team","noun","团队"),("department","noun","部门"),
    ("division","noun","部门"),("branch","noun","分部"),("headquarters","noun","总部"),
    ("meeting","noun","会议"),("conference","noun","大会"),("presentation","noun","演示"),
    ("report","noun","报告"),("proposal","noun","提案"),("project","noun","项目"),("task","noun","任务"),
    ("assignment","noun","任务"),("deadline","noun","截止日期"),("schedule","noun","日程"),
    ("shift","noun","轮班"),("overtime","noun","加班"),("salary","noun","工资"),("wage","noun","工资"),
    ("bonus","noun","奖金"),("commission","noun","佣金"),("promotion","noun","晋升"),
    ("demotion","noun","降职"),("resign","verb","辞职"),("retire","verb","退休"),
    ("hire","verb","雇佣"),("fire","verb","解雇"),("dismiss","verb","解雇"),("lay off","verb","裁员"),
    ("apply","verb","申请"),("interview","noun","面试"),("resume","noun","简历"),
    ("qualification","noun","资格"),("experience","noun","经验"),("skill","noun","技能"),
    ("training","noun","培训"),("workshop","noun","研讨会"),("seminar","noun","讲座"),
    ("client","noun","客户"),("customer","noun","顾客"),("contract","noun","合同"),
    ("agreement","noun","协议"),("negotiate","verb","谈判"),("deal","noun","交易"),
    ("profit","noun","利润"),("revenue","noun","收入"),("expense","noun","支出"),
    ("budget","noun","预算"),("investment","noun","投资"),("strategy","noun","策略"),
    ("goal","noun","目标"),("target","noun","指标"),("performance","noun","绩效"),
    ("efficiency","noun","效率"),("productivity","noun","生产力"),("quality","noun","质量"),
    ("innovation","noun","创新"),("competition","noun","竞争"),("market","noun","市场"),
    ("industry","noun","行业"),("company","noun","公司"),("corporation","noun","企业"),
    ("enterprise","noun","企业"),("startup","noun","初创公司"),("partnership","noun","合伙企业"),
    ("freelance","noun","自由职业"),("entrepreneur","noun","企业家"),("businessman","noun","商人"),
    ("communicate","verb","沟通"),("collaborate","verb","合作"),("coordinate","verb","协调"),
    ("delegate","verb","委派"),("supervise","verb","监督"),("evaluate","verb","评估"),
    ("implement","verb","实施"),("achieve","verb","达成"),("accomplish","verb","完成"),
    ("succeed","verb","成功"),("fail","verb","失败"),("improve","verb","改进"),
    ("organize","verb","组织"),("prioritize","verb","优先排序"),("delegate","verb","授权"),
    ("decision","noun","决定"),("solution","noun","解决方案"),("feedback","noun","反馈"),
    ("complaint","noun","投诉"),("suggestion","noun","建议"),("approval","noun","批准"),
    ("permission","noun","许可"),("policy","noun","政策"),("procedure","noun","程序"),
    ("regulation","noun","规章"),("standard","noun","标准"),("guideline","noun","指导方针"),
    ("professional","adj","专业的"),("efficient","adj","高效的"),("reliable","adj","可靠的"),
    ("responsible","adj","负责的"),("punctual","adj","准时的"),("flexible","adj","灵活的"),
    ("creative","adj","创造性的"),("ambitious","adj","有雄心的"),("diligent","adj","勤奋的"),
    ("competent","adj","胜任的"),("qualified","adj","合格的"),("experienced","adj","有经验的"),
    ("part-time","adj","兼职的"),("full-time","adj","全职的"),("temporary","adj","临时的"),
    ("permanent","adj","永久的"),("vacancy","noun","职位空缺"),("recruit","verb","招聘"),
    ("candidate","noun","候选人"),("reference","noun","推荐信"),("portfolio","noun","作品集"),
]

EDUCATION = [
    ("school","noun","学校"),("university","noun","大学"),("college","noun","学院"),("academy","noun","学院"),
    ("kindergarten","noun","幼儿园"),("primary school","noun","小学"),("secondary school","noun","中学"),
    ("high school","noun","高中"),("graduate","verb","毕业"),("enroll","verb","注册"),
    ("student","noun","学生"),("teacher","noun","老师"),("professor","noun","教授"),
    ("lecturer","noun","讲师"),("principal","noun","校长"),("classmate","noun","同学"),
    ("classroom","noun","教室"),("library","noun","图书馆"),("laboratory","noun","实验室"),
    ("campus","noun","校园"),("dormitory","noun","宿舍"),("cafeteria","noun","食堂"),
    ("course","noun","课程"),("subject","noun","科目"),("lesson","noun","课"),("class","noun","班级；课"),
    ("lecture","noun","讲座"),("seminar","noun","研讨会"),("tutorial","noun","辅导课"),
    ("exam","noun","考试"),("test","noun","测试"),("quiz","noun","小测验"),("assignment","noun","作业"),
    ("homework","noun","家庭作业"),("project","noun","项目"),("thesis","noun","论文"),
    ("dissertation","noun","学位论文"),("essay","noun","文章"),("report","noun","报告"),
    ("presentation","noun","演示"),("grade","noun","成绩"),("score","noun","分数"),("mark","noun","分数"),
    ("degree","noun","学位"),("diploma","noun","毕业证"),("certificate","noun","证书"),
    ("scholarship","noun","奖学金"),("tuition","noun","学费"),("fee","noun","费用"),
    ("mathematics","noun","数学"),("science","noun","科学"),("literature","noun","文学"),
    ("history","noun","历史"),("geography","noun","地理"),("physics","noun","物理"),
    ("chemistry","noun","化学"),("biology","noun","生物"),("language","noun","语言"),
    ("art","noun","艺术"),("music","noun","音乐"),("physical education","noun","体育"),
    ("computer science","noun","计算机科学"),("economics","noun","经济学"),("philosophy","noun","哲学"),
    ("psychology","noun","心理学"),("sociology","noun","社会学"),("engineering","noun","工程学"),
    ("medicine","noun","医学"),("law","noun","法律"),("business","noun","商业"),
    ("study","verb","学习"),("learn","verb","学习"),("teach","verb","教授"),("read","verb","阅读"),
    ("write","verb","写作"),("research","noun","研究"),("analyze","verb","分析"),
    ("discuss","verb","讨论"),("review","verb","复习"),("practice","verb","练习"),
    ("memorize","verb","记忆"),("understand","verb","理解"),("explain","verb","解释"),
    ("knowledge","noun","知识"),("wisdom","noun","智慧"),("skill","noun","技能"),
    ("ability","noun","能力"),("talent","noun","天赋"),("intelligence","noun","智力"),
    ("curriculum","noun","课程体系"),("syllabus","noun","教学大纲"),("textbook","noun","教科书"),
    ("notebook","noun","笔记本"),("pen","noun","钢笔"),("pencil","noun","铅笔"),
    ("eraser","noun","橡皮"),("ruler","noun","尺子"),("backpack","noun","书包"),
    ("dictionary","noun","词典"),("encyclopedia","noun","百科全书"),("journal","noun","期刊"),
    ("publish","verb","出版"),("author","noun","作者"),("chapter","noun","章节"),
    ("paragraph","noun","段落"),("sentence","noun","句子"),("vocabulary","noun","词汇"),
    ("grammar","noun","语法"),("pronunciation","noun","发音"),("spelling","noun","拼写"),
    ("composition","noun","作文"),("comprehension","noun","理解力"),("fluency","noun","流利"),
    ("bilingual","adj","双语的"),("literacy","noun","读写能力"),("numeracy","noun","算术能力"),
    ("academic","adj","学术的"),("educational","adj","教育的"),("compulsory","adj","义务的"),
    ("optional","adj","可选的"),("extracurricular","adj","课外的"),("semester","noun","学期"),
    ("term","noun","学期"),("academic year","noun","学年"),("graduation","noun","毕业典礼"),
    ("commencement","noun","毕业典礼"),("alumnus","noun","校友"),("faculty","noun","教职员工"),
    ("dean","noun","院长"),("chancellor","noun","校长"),("rector","noun","校长"),
]

TRANSPORT = [
    ("car","noun","汽车"),("bus","noun","公交车"),("train","noun","火车"),("subway","noun","地铁"),
    ("taxi","noun","出租车"),("bicycle","noun","自行车"),("motorcycle","noun","摩托车"),
    ("scooter","noun","踏板车"),("truck","noun","卡车"),("van","noun","面包车"),
    ("ambulance","noun","救护车"),("fire engine","noun","消防车"),("police car","noun","警车"),
    ("airplane","noun","飞机"),("helicopter","noun","直升机"),("ship","noun","船"),
    ("boat","noun","小船"),("ferry","noun","渡轮"),("yacht","noun","游艇"),
    ("road","noun","道路"),("street","noun","街道"),("avenue","noun","大道"),("lane","noun","小巷"),
    ("highway","noun","高速公路"),("freeway","noun","高速公路"),("intersection","noun","十字路口"),
    ("crossroad","noun","交叉路口"),("roundabout","noun","环岛"),("bridge","noun","桥"),
    ("tunnel","noun","隧道"),("overpass","noun","天桥"),("underpass","noun","地下通道"),
    ("sidewalk","noun","人行道"),("crosswalk","noun","斑马线"),("parking lot","noun","停车场"),
    ("garage","noun","车库"),("gas station","noun","加油站"),("traffic light","noun","红绿灯"),
    ("stop sign","noun","停车标志"),("speed limit","noun","限速"),("seatbelt","noun","安全带"),
    ("driver","noun","司机"),("passenger","noun","乘客"),("pedestrian","noun","行人"),
    ("cyclist","noun","骑车人"),("commuter","noun","通勤者"),("traffic","noun","交通"),
    ("jam","noun","拥堵"),("rush hour","noun","高峰期"),("congestion","noun","拥堵"),
    ("accident","noun","事故"),("collision","noun","碰撞"),("crash","noun","撞车"),
    ("breakdown","noun","故障"),("flat tire","noun","爆胎"),("engine","noun","引擎"),
    ("brake","noun","刹车"),("steering wheel","noun","方向盘"),("mirror","noun","后视镜"),
    ("horn","noun","喇叭"),("headlight","noun","前灯"),("taillight","noun","尾灯"),
    ("tire","noun","轮胎"),("wheel","noun","车轮"),("exhaust","noun","排气"),
    ("fuel","noun","燃料"),("gasoline","noun","汽油"),("diesel","noun","柴油"),
    ("electric","adj","电动的"),("hybrid","adj","混合动力的"),("autonomous","adj","自动驾驶的"),
    ("drive","verb","开车"),("ride","verb","骑车；乘坐"),("park","verb","停车"),
    ("reverse","verb","倒车"),("overtake","verb","超车"),("yield","verb","让行"),
    ("commute","verb","通勤"),("depart","verb","出发"),("arrive","verb","到达"),
    ("transport","verb","运输"),("deliver","verb","递送"),("ship","verb","运输"),
    ("route","noun","路线"),("destination","noun","目的地"),("departure","noun","出发"),
    ("arrival","noun","到达"),("schedule","noun","时刻表"),("timetable","noun","时间表"),
    ("fare","noun","票价"),("ticket","noun","票"),("pass","noun","通行证"),
    ("platform","noun","站台"),("terminal","noun","航站楼"),("station","noun","车站"),
    ("port","noun","港口"),("harbor","noun","港湾"),("dock","noun","码头"),
    ("lane","noun","车道"),("expressway","noun","快速路"),("toll","noun","过路费"),
    ("navigation","noun","导航"),("GPS","noun","全球定位系统"),("map","noun","地图"),
    ("direction","noun","方向"),("distance","noun","距离"),("mileage","noun","里程"),
    ("journey","noun","旅程"),("trip","noun","旅行"),("voyage","noun","航行"),
    ("cargo","noun","货物"),("freight","noun","货运"),("logistics","noun","物流"),
    ("vehicle","noun","车辆"),("automobile","noun","汽车"),("transit","noun","公共交通"),
]

HEALTH = [
    ("health","noun","健康"),("healthy","adj","健康的"),("sick","adj","生病的"),("ill","adj","生病的"),
    ("disease","noun","疾病"),("illness","noun","病"),("condition","noun","状况"),("symptom","noun","症状"),
    ("fever","noun","发烧"),("cough","noun","咳嗽"),("headache","noun","头痛"),("stomachache","noun","胃痛"),
    ("toothache","noun","牙痛"),("backache","noun","背痛"),("sore throat","noun","喉咙痛"),
    ("cold","noun","感冒"),("flu","noun","流感"),("allergy","noun","过敏"),("infection","noun","感染"),
    ("virus","noun","病毒"),("bacteria","noun","细菌"),("injury","noun","伤害"),("wound","noun","伤口"),
    ("bruise","noun","瘀伤"),("fracture","noun","骨折"),("sprain","noun","扭伤"),
    ("cut","noun","割伤"),("burn","noun","烧伤"),("bleeding","noun","出血"),
    ("pain","noun","疼痛"),("ache","noun","疼痛"),("nausea","noun","恶心"),("dizziness","noun","头晕"),
    ("fatigue","noun","疲劳"),("insomnia","noun","失眠"),("stress","noun","压力"),
    ("anxiety","noun","焦虑"),("depression","noun","抑郁"),("obesity","noun","肥胖"),
    ("diabetes","noun","糖尿病"),("hypertension","noun","高血压"),("asthma","noun","哮喘"),
    ("arthritis","noun","关节炎"),("cancer","noun","癌症"),("pneumonia","noun","肺炎"),
    ("stroke","noun","中风"),("heart attack","noun","心脏病发作"),
    ("doctor","noun","医生"),("nurse","noun","护士"),("surgeon","noun","外科医生"),
    ("physician","noun","内科医生"),("dentist","noun","牙医"),("pharmacist","noun","药剂师"),
    ("therapist","noun","治疗师"),("psychiatrist","noun","精神科医生"),("specialist","noun","专家"),
    ("hospital","noun","医院"),("clinic","noun","诊所"),("pharmacy","noun","药店"),
    ("emergency room","noun","急诊室"),("ward","noun","病房"),("operating room","noun","手术室"),
    ("medicine","noun","药物"),("drug","noun","药"),("pill","noun","药片"),("tablet","noun","药片"),
    ("capsule","noun","胶囊"),("prescription","noun","处方"),("dosage","noun","剂量"),
    ("vaccine","noun","疫苗"),("injection","noun","注射"),("needle","noun","针"),
    ("bandage","noun","绷带"),("plaster","noun","膏药"),("antibiotic","noun","抗生素"),
    ("painkiller","noun","止痛药"),("vitamin","noun","维生素"),("supplement","noun","补充剂"),
    ("examine","verb","检查"),("diagnose","verb","诊断"),("treat","verb","治疗"),
    ("cure","verb","治愈"),("heal","verb","愈合"),("recover","verb","康复"),
    ("prevent","verb","预防"),("operate","verb","手术"),("prescribe","verb","开处方"),
    ("surgery","noun","手术"),("transplant","noun","移植"),("therapy","noun","治疗"),
    ("rehabilitation","noun","康复"),("check-up","noun","体检"),("blood test","noun","验血"),
    ("X-ray","noun","X光"),("scan","noun","扫描"),("ultrasound","noun","超声波"),
    ("blood pressure","noun","血压"),("pulse","noun","脉搏"),("temperature","noun","体温"),
    ("diet","noun","饮食"),("exercise","noun","锻炼"),("sleep","noun","睡眠"),
    ("hygiene","noun","卫生"),("nutrition","noun","营养"),("wellness","noun","健康"),
    ("immune system","noun","免疫系统"),("mental health","noun","心理健康"),
    ("physical health","noun","身体健康"),("first aid","noun","急救"),
    ("CPR","noun","心肺复苏"),("ambulance","noun","救护车"),
    ("chronic","adj","慢性的"),("acute","adj","急性的"),("contagious","adj","传染的"),
    ("terminal","adj","晚期的"),("mild","adj","轻微的"),("severe","adj","严重的"),
    ("contagious","adj","有传染性的"),("infectious","adj","传染性的"),
]

NATURE = [
    ("nature","noun","自然"),("environment","noun","环境"),("ecology","noun","生态"),
    ("animal","noun","动物"),("plant","noun","植物"),("tree","noun","树"),("flower","noun","花"),
    ("grass","noun","草"),("bush","noun","灌木"),("shrub","noun","灌木"),("weed","noun","杂草"),
    ("forest","noun","森林"),("jungle","noun","丛林"),("woodland","noun","林地"),("meadow","noun","草地"),
    ("desert","noun","沙漠"),("wetland","noun","湿地"),("swamp","noun","沼泽"),("prairie","noun","草原"),
    ("mountain","noun","山"),("hill","noun","小山"),("valley","noun","山谷"),("canyon","noun","峡谷"),
    ("cliff","noun","悬崖"),("cave","noun","洞穴"),("volcano","noun","火山"),("glacier","noun","冰川"),
    ("river","noun","河流"),("stream","noun","溪流"),("lake","noun","湖"),("pond","noun","池塘"),
    ("ocean","noun","海洋"),("sea","noun","海"),("bay","noun","海湾"),("gulf","noun","海湾"),
    ("coast","noun","海岸"),("shore","noun","岸"),("beach","noun","海滩"),("island","noun","岛"),
    ("peninsula","noun","半岛"),("continent","noun","大陆"),("earth","noun","地球"),
    ("sky","noun","天空"),("star","noun","星星"),("moon","noun","月亮"),("sun","noun","太阳"),
    ("cloud","noun","云"),("rain","noun","雨"),("snow","noun","雪"),("wind","noun","风"),
    ("storm","noun","暴风雨"),("thunder","noun","雷"),("lightning","noun","闪电"),
    ("rainbow","noun","彩虹"),("fog","noun","雾"),("dew","noun","露水"),
    ("bird","noun","鸟"),("fish","noun","鱼"),("insect","noun","昆虫"),("butterfly","noun","蝴蝶"),
    ("bee","noun","蜜蜂"),("ant","noun","蚂蚁"),("spider","noun","蜘蛛"),("mosquito","noun","蚊子"),
    ("fly","noun","苍蝇"),("worm","noun","虫"),("snail","noun","蜗牛"),
    ("dog","noun","狗"),("cat","noun","猫"),("horse","noun","马"),("cow","noun","牛"),
    ("pig","noun","猪"),("sheep","noun","羊"),("goat","noun","山羊"),("chicken","noun","鸡"),
    ("duck","noun","鸭"),("rabbit","noun","兔子"),("mouse","noun","老鼠"),("rat","noun","老鼠"),
    ("lion","noun","狮子"),("tiger","noun","老虎"),("bear","noun","熊"),("elephant","noun","大象"),
    ("monkey","noun","猴子"),("snake","noun","蛇"),("frog","noun","青蛙"),("turtle","noun","海龟"),
    ("whale","noun","鲸"),("dolphin","noun","海豚"),("shark","noun","鲨鱼"),("eagle","noun","鹰"),
    ("owl","noun","猫头鹰"),("parrot","noun","鹦鹉"),("penguin","noun","企鹅"),("swan","noun","天鹅"),
    ("rose","noun","玫瑰"),("lily","noun","百合"),("tulip","noun","郁金香"),("daisy","noun","雏菊"),
    ("sunflower","noun","向日葵"),("orchid","noun","兰花"),("cactus","noun","仙人掌"),
    ("bamboo","noun","竹子"),("oak","noun","橡树"),("pine","noun","松树"),("willow","noun","柳树"),
    ("maple","noun","枫树"),("palm","noun","棕榈树"),("trunk","noun","树干"),("branch","noun","树枝"),
    ("leaf","noun","叶子"),("root","noun","根"),("seed","noun","种子"),("fruit","noun","果实"),
    ("petal","noun","花瓣"),("pollen","noun","花粉"),("soil","noun","土壤"),("sand","noun","沙子"),
    ("rock","noun","岩石"),("stone","noun","石头"),("mineral","noun","矿物"),("crystal","noun","水晶"),
    ("fossil","noun","化石"),("erode","verb","侵蚀"),("evolve","verb","进化"),
    ("bloom","verb","开花"),("wither","verb","枯萎"),("grow","verb","生长"),("sprout","verb","发芽"),
    ("endangered","adj","濒危的"),("extinct","adj","灭绝的"),("wild","adj","野生的"),
    ("domestic","adj","驯养的"),("marine","adj","海洋的"),("tropical","adj","热带的"),
    ("arctic","adj","北极的"),("polar","adj","极地的"),("ecosystem","noun","生态系统"),
    ("biodiversity","noun","生物多样性"),("conservation","noun","保护"),("sustainability","noun","可持续性"),
    ("pollution","noun","污染"),("deforestation","noun","砍伐森林"),("erosion","noun","侵蚀"),
    ("habitat","noun","栖息地"),("wildlife","noun","野生动物"),
]

CLOTHING = [
    ("shirt","noun","衬衫"),("blouse","noun","女衬衫"),("t-shirt","noun","T恤"),("sweater","noun","毛衣"),
    ("jacket","noun","夹克"),("coat","noun","外套"),("suit","noun","西装"),("dress","noun","连衣裙"),
    ("skirt","noun","裙子"),("pants","noun","裤子"),("trousers","noun","裤子(英式)"),("jeans","noun","牛仔裤"),
    ("shorts","noun","短裤"),("underwear","noun","内衣"),("sock","noun","袜子"),("stocking","noun","长筒袜"),
    ("shoe","noun","鞋子"),("boot","noun","靴子"),("sandal","noun","凉鞋"),("sneaker","noun","运动鞋"),
    ("heel","noun","高跟鞋"),("slipper","noun","拖鞋"),("hat","noun","帽子"),("cap","noun","鸭舌帽"),
    ("scarf","noun","围巾"),("glove","noun","手套"),("belt","noun","皮带"),("tie","noun","领带"),
    ("bow tie","noun","领结"),("vest","noun","马甲"),("hoodie","noun","卫衣"),("cardigan","noun","开衫"),
    ("pajamas","noun","睡衣"),("swimsuit","noun","泳衣"),("uniform","noun","制服"),
    ("raincoat","noun","雨衣"),("overcoat","noun","大衣"),("blazer","noun","运动外套"),
    ("waistcoat","noun","马甲"),("tank top","noun","背心"),("polo shirt","noun","Polo衫"),
    ("collar","noun","领子"),("sleeve","noun","袖子"),("pocket","noun","口袋"),("button","noun","纽扣"),
    ("zipper","noun","拉链"),("hem","noun","裙摆"),("seam","noun","缝线"),("cuff","noun","袖口"),
    ("fabric","noun","面料"),("cotton","noun","棉"),("silk","noun","丝绸"),("wool","noun","羊毛"),
    ("leather","noun","皮革"),("denim","noun","牛仔布"),("linen","noun","亚麻"),("velvet","noun","天鹅绒"),
    ("satin","noun","缎子"),("polyester","noun","涤纶"),("nylon","noun","尼龙"),
    ("lace","noun","蕾丝"),("knit","noun","针织"),("pattern","noun","图案"),("stripe","noun","条纹"),
    ("plaid","noun","格子"),("polka dot","noun","波点"),("floral","adj","花卉的"),
    ("wear","verb","穿"),("put on","verb","穿上"),("take off","verb","脱下"),
    ("try on","verb","试穿"),("fit","verb","合身"),("match","verb","搭配"),
    ("dress up","verb","盛装"),("dress down","verb","穿便装"),("change","verb","换衣服"),
    ("fold","verb","折叠"),("hang","verb","悬挂"),("iron","verb","熨烫"),
    ("sew","verb","缝纫"),("stitch","verb","缝合"),("mend","verb","修补"),
    ("tailor","noun","裁缝"),("designer","noun","设计师"),("boutique","noun","精品店"),
    ("wardrobe","noun","衣柜"),("closet","noun","壁橱"),("drawer","noun","抽屉"),
    ("hanger","noun","衣架"),("laundry","noun","待洗衣物"),("dry clean","verb","干洗"),
    ("fashionable","adj","时髦的"),("elegant","adj","优雅的"),("casual","adj","休闲的"),
    ("formal","adj","正式的"),("stylish","adj","时尚的"),("trendy","adj","流行的"),
    ("vintage","adj","复古的"),("classic","adj","经典的"),("comfortable","adj","舒适的"),
    ("tight","adj","紧的"),("loose","adj","松的"),("long","adj","长的"),("short","adj","短的"),
    ("large","adj","大的"),("small","adj","小的"),("medium","adj","中号的"),
    ("accessory","noun","配饰"),("necklace","noun","项链"),("bracelet","noun","手镯"),
    ("earring","noun","耳环"),("ring","noun","戒指"),("watch","noun","手表"),
    ("purse","noun","手提包"),("wallet","noun","钱包"),("backpack","noun","背包"),
    ("sunglasses","noun","太阳镜"),("umbrella","noun","雨伞"),
]

MONEY = [
    ("money","noun","钱"),("cash","noun","现金"),("coin","noun","硬币"),("bill","noun","纸币"),
    ("currency","noun","货币"),("dollar","noun","美元"),("euro","noun","欧元"),("pound","noun","英镑"),
    ("yen","noun","日元"),("yuan","noun","人民币"),("bank","noun","银行"),("account","noun","账户"),
    ("deposit","noun","存款"),("withdraw","verb","取款"),("transfer","verb","转账"),
    ("savings","noun","储蓄"),("interest","noun","利息"),("loan","noun","贷款"),
    ("mortgage","noun","房贷"),("debt","noun","债务"),("credit","noun","信用"),
    ("debit","noun","借记"),("balance","noun","余额"),("statement","noun","对账单"),
    ("receipt","noun","收据"),("invoice","noun","发票"),("tax","noun","税"),("income tax","noun","所得税"),
    ("salary","noun","工资"),("wage","noun","工资"),("income","noun","收入"),
    ("expense","noun","支出"),("cost","noun","费用"),("price","noun","价格"),
    ("profit","noun","利润"),("loss","noun","亏损"),("revenue","noun","收入"),
    ("budget","noun","预算"),("invest","verb","投资"),("investment","noun","投资"),
    ("stock","noun","股票"),("bond","noun","债券"),("fund","noun","基金"),
    ("share","noun","股份"),("dividend","noun","股息"),("portfolio","noun","投资组合"),
    ("market","noun","市场"),("economy","noun","经济"),("inflation","noun","通货膨胀"),
    ("deflation","noun","通货紧缩"),("recession","noun","经济衰退"),("growth","noun","增长"),
    ("trade","noun","贸易"),("export","noun","出口"),("import","noun","进口"),
    ("commerce","noun","商业"),("business","noun","生意"),("transaction","noun","交易"),
    ("purchase","noun","购买"),("payment","noun","付款"),("refund","noun","退款"),
    ("discount","noun","折扣"),("bargain","noun","便宜货"),("wholesale","noun","批发"),
    ("retail","noun","零售"),("insurance","noun","保险"),("premium","noun","保险费"),
    ("claim","noun","索赔"),("policy","noun","保单"),("coverage","noun","保险范围"),
    ("real estate","noun","房地产"),("property","noun","房产"),("rent","noun","租金"),
    ("lease","noun","租约"),("tenant","noun","租户"),("landlord","noun","房东"),
    ("wealth","noun","财富"),("fortune","noun","财富"),("poverty","noun","贫困"),
    ("afford","verb","买得起"),("save","verb","储蓄"),("spend","verb","花费"),
    ("waste","verb","浪费"),("earn","verb","赚取"),("pay","verb","付款"),
    ("charge","verb","收费"),("cost","verb","花费"),("finance","noun","金融"),
    ("financial","adj","金融的"),("economic","adj","经济的"),("commercial","adj","商业的"),
    ("affordable","adj","负担得起的"),("expensive","adj","昂贵的"),("cheap","adj","便宜的"),
    ("valuable","adj","有价值的"),("profitable","adj","盈利的"),("bankrupt","adj","破产的"),
    ("broke","adj","身无分文的"),("wealthy","adj","富有的"),("poor","adj","贫穷的"),
    ("ATM","noun","自动取款机"),("credit card","noun","信用卡"),("debit card","noun","借记卡"),
    ("pin","noun","密码"),("online banking","noun","网上银行"),("exchange rate","noun","汇率"),
    ("capital","noun","资本"),("asset","noun","资产"),("liability","noun","负债"),
    ("equity","noun","权益"),("audit","noun","审计"),("accountant","noun","会计师"),
    ("charity","noun","慈善"),("donation","noun","捐赠"),("scholarship","noun","奖学金"),
    ("pension","noun","养老金"),("retirement","noun","退休"),("allowance","noun","零花钱"),
    ("commission","noun","佣金"),("bonus","noun","奖金"),("overtime pay","noun","加班费"),
    ("tip","noun","小费"),("fine","noun","罚款"),("fee","noun","费用"),("tuition","noun","学费"),
    ("fare","noun","票价"),("toll","noun","过路费"),("subsidy","noun","补贴"),
    ("banknote","noun","纸币"),("change","noun","零钱"),("installment","noun","分期付款"),
    ("pawn","verb","典当"),("mortgage","verb","抵押"),("collateral","noun","抵押品"),
]

SOCIAL = [
    ("friend","noun","朋友"),("friendship","noun","友谊"),("colleague","noun","同事"),
    ("neighbor","noun","邻居"),("partner","noun","伙伴"),("companion","noun","伴侣"),
    ("acquaintance","noun","熟人"),("stranger","noun","陌生人"),("guest","noun","客人"),
    ("host","noun","主人"),("hostess","noun","女主人"),("visitor","noun","访客"),
    ("family","noun","家庭"),("parent","noun","父母"),("mother","noun","母亲"),("father","noun","父亲"),
    ("sister","noun","姐妹"),("brother","noun","兄弟"),("daughter","noun","女儿"),("son","noun","儿子"),
    ("grandparent","noun","祖父母"),("grandmother","noun","祖母"),("grandfather","noun","祖父"),
    ("grandchild","noun","孙辈"),("aunt","noun","阿姨"),("uncle","noun","叔叔"),
    ("cousin","noun","堂/表亲"),("nephew","noun","侄子"),("niece","noun","侄女"),
    ("husband","noun","丈夫"),("wife","noun","妻子"),("couple","noun","夫妻"),
    ("greet","verb","问候"),("wave","verb","挥手"),("hug","verb","拥抱"),("kiss","verb","亲吻"),
    ("shake hands","verb","握手"),("bow","verb","鞠躬"),("nod","verb","点头"),
    ("smile","verb","微笑"),("laugh","verb","笑"),("cry","verb","哭"),
    ("chat","verb","聊天"),("talk","verb","谈话"),("discuss","verb","讨论"),
    ("argue","verb","争论"),("debate","verb","辩论"),("agree","verb","同意"),("disagree","verb","不同意"),
    ("apologize","verb","道歉"),("forgive","verb","原谅"),("complain","verb","抱怨"),
    ("praise","verb","赞扬"),("criticize","verb","批评"),("encourage","verb","鼓励"),
    ("comfort","verb","安慰"),("support","verb","支持"),("help","verb","帮助"),
    ("assist","verb","协助"),("cooperate","verb","合作"),("collaborate","verb","协作"),
    ("share","verb","分享"),("trust","verb","信任"),("respect","verb","尊重"),
    ("admire","verb","钦佩"),("appreciate","verb","感激"),("thank","verb","感谢"),
    ("invite","verb","邀请"),("welcome","verb","欢迎"),("introduce","verb","介绍"),
    ("recommend","verb","推荐"),("suggest","verb","建议"),("advise","verb","忠告"),
    ("persuade","verb","说服"),("convince","verb","使信服"),("influence","verb","影响"),
    ("impress","verb","给…留下印象"),("disappoint","verb","使失望"),("annoy","verb","使烦恼"),
    ("offend","verb","冒犯"),("insult","verb","侮辱"),("ignore","verb","忽视"),
    ("avoid","verb","避免"),("reject","verb","拒绝"),("accept","verb","接受"),
    ("celebrate","verb","庆祝"),("congratulate","verb","祝贺"),("participate","verb","参与"),
    ("join","verb","加入"),("attend","verb","出席"),("organize","verb","组织"),
    ("party","noun","派对"),("ceremony","noun","典礼"),("festival","noun","节日"),
    ("holiday","noun","假日"),("vacation","noun","假期"),("anniversary","noun","纪念日"),
    ("birthday","noun","生日"),("wedding","noun","婚礼"),("funeral","noun","葬礼"),
    ("gift","noun","礼物"),("present","noun","礼物"),("surprise","noun","惊喜"),
    ("communication","noun","沟通"),("conversation","noun","对话"),("dialogue","noun","对话"),
    ("speech","noun","演讲"),("message","noun","消息"),("letter","noun","信"),
    ("email","noun","电子邮件"),("phone","noun","电话"),("call","verb","打电话"),
    ("text","verb","发短信"),("social media","noun","社交媒体"),("network","noun","网络"),
    ("community","noun","社区"),("society","noun","社会"),("culture","noun","文化"),
    ("tradition","noun","传统"),("custom","noun","习俗"),("habit","noun","习惯"),
    ("manner","noun","礼貌"),("etiquette","noun","礼仪"),("polite","adj","礼貌的"),
    ("rude","adj","粗鲁的"),("kind","adj","善良的"),("generous","adj","慷慨的"),
    ("selfish","adj","自私的"),("honest","adj","诚实的"),("loyal","adj","忠诚的"),
    ("sincere","adj","真诚的"),("reliable","adj","可靠的"),("trustworthy","adj","值得信赖的"),
    ("patient","adj","耐心的"),("tolerant","adj","宽容的"),("modest","adj","谦虚的"),
    ("proud","adj","骄傲的"),("confident","adj","自信的"),("shy","adj","害羞的"),
    ("outgoing","adj","外向的"),("introverted","adj","内向的"),("extroverted","adj","外向的"),
    ("friendly","adj","友好的"),("hostile","adj","敌意的"),("warm","adj","热情的"),
    ("cold","adj","冷淡的"),("considerate","adj","体贴的"),("thoughtful","adj","周到的"),
]

CATEGORIES = {
    "food": FOOD,
    "travel": TRAVEL,
    "shopping": SHOPPING,
    "home": HOME,
    "body": BODY,
    "weather": WEATHER,
    "emotion": EMOTION,
    "work": WORK,
    "education": EDUCATION,
    "transport": TRANSPORT,
    "health": HEALTH,
    "nature": NATURE,
    "clothing": CLOTHING,
    "money": MONEY,
    "social": SOCIAL,
}


def _build_category(name, words):
    result = []
    for i, w in enumerate(words):
        result.append({
            "word": w[0],
            "phonetic": "",
            "pos": w[1],
            "meaning_cn": w[2],
            "category": name,
            "frequency_rank": (i + 1) * 3,
            "example_en": "",
            "example_cn": "",
        })
    return result


def generate():
    all_words = []
    for cat_name, cat_words in CATEGORIES.items():
        all_words.extend(_build_category(cat_name, cat_words))

    os.makedirs(os.path.join(os.path.dirname(__file__), "data"), exist_ok=True)
    with open(WORDS_JSON, "w", encoding="utf-8") as f:
        json.dump(all_words, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(all_words)} words to {WORDS_JSON}")


if __name__ == "__main__":
    generate()
